import fs from 'node:fs';
import path from 'node:path';
import { MARS_ROOT, VERSION_FILE } from './paths.mjs';
import { parseFlatYaml, writeFlatYaml } from './yaml.mjs';

export const MARS_VERSION = fs.readFileSync(VERSION_FILE, 'utf8').trim();
export const DESIGN_API = '1';
export const CONTENT_MODEL = 'stack-brick-deck-slide';
export const THEME_VERSION = '1.0.0';

export function packageInfo() {
  try { return JSON.parse(fs.readFileSync(path.join(MARS_ROOT, 'package.json'), 'utf8')); }
  catch { return {}; }
}

export function marpCliVersion() {
  return packageInfo()?.dependencies?.['@marp-team/marp-cli'] || 'unknown';
}

export function lockPath(stackRoot) { return path.join(stackRoot, 'mars.lock'); }
export function readMarsLock(stackRoot) {
  const file = lockPath(stackRoot);
  return fs.existsSync(file) ? parseFlatYaml(file) : {};
}

export function writeMarsLock(stackRoot, { shortTitle = '', theme = 'mars', profile = '', kind = 'stack' } = {}) {
  const data = {
    schema: 3,
    'mars.version': MARS_VERSION,
    'content.model': CONTENT_MODEL,
    'design.api': DESIGN_API,
    'marp_cli.version': marpCliVersion(),
    'theme.name': theme,
    'theme.version': THEME_VERSION,
    'institution.profile': profile,
    'stack.short_title': shortTitle,
    'root.kind': kind,
    'node.minimum': 18,
  };
  writeFlatYaml(lockPath(stackRoot), data, 'Generated by MARS. Commit this file for reproducible builds.');
  return data;
}

export function minorLine(version) {
  const m = String(version || '').match(/^(\d+)\.(\d+)/);
  return m ? `${m[1]}.${m[2]}` : String(version || '');
}

export function lockCompatibility(stackRoot) {
  const lock = readMarsLock(stackRoot);
  const locked = lock['mars.version'] || lock.mars || '';
  if (!locked) return { ok: false, missing: true, locked: '', current: MARS_VERSION };
  return { ok: minorLine(locked) === minorLine(MARS_VERSION), missing: false, locked, current: MARS_VERSION };
}
